[package]
org = "gha-indie-worker"
name = "gha-indie-worker-interfaces"
version = "0.1.0"
language = "rust"

[package.repository]
vcs = "git"
url = "https://github.com/gha-indie-worker/gha-indie-worker-interfaces"

[dev-dependencies]
"oresoftware/ores-contracts" = "^0.1.0"
